FROM henriqueslab/dl4miceverywhere:u-net_3d_zerocostdl4mic-z2.1.3-d2.0.0-gpu

RUN pip install neptune
RUN pip install -U neptune-tensorflow-keras

WORKDIR /


COPY Dockerfile.txt ./Dockerfile.txt


CMD ["python"]