function_10_add_additive_gaussian_noise: true
function_10_add_custom_augmenters: false
function_10_add_elastic_deform: false
function_10_add_gaussian_blur: true
function_10_add_linear_contrast: true
function_10_apply_data_augmentation: true
function_10_augmenters: ''
function_10_contrast_frequency: 0.5
function_10_contrast_max: 1.6
function_10_contrast_min: 0.4
function_10_gaussian_frequency: 0.5
function_10_gaussian_sigma: 0.7
function_10_noise_frequency: 0.5
function_10_order: 1
function_10_points: 2
function_10_scale_max: 0.05
function_10_scale_min: 0
function_10_sigma: 2
function_8_batch_size: 1
function_8_binary_target: true
function_8_checkpoint_path: ''
function_8_checkpointing_period: 1
function_8_downscaling_in_xy: 1
function_8_image_pre_processing: randomly crop to patch_size
function_8_learning_rate: 0.001
function_8_loss_function: weighted_binary_crossentropy
function_8_metrics: dice
function_8_model_id: ''
function_8_model_name: testmodel
function_8_model_path: data/test_model
function_8_number_of_epochs: 10
function_8_optimizer: adam
function_8_patch_size:
- 512
- 512
- 8
function_8_pretrained_model_choice: Model_from_file
function_8_resume_training: false
function_8_save_best_only: false
function_8_training_source: data/source
function_8_training_target: data/target
function_8_use_default_advanced_parameters: true
function_8_validation_split_in_percent: 20
